kind: pipeline
name: default

steps:
  - name: build and test
    image: xd009642/tarpaulin
    commands:
      - cargo build --verbose --all
      - cargo test --verbose --all
  - name: coverage
    image: xd009642/tarpaulin
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
    commands:
      - cargo tarpaulin --out Xml
      - bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN
    when:
      status:
        - failure
        - success
